# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1414aa587bbea786fdf650fd8b2fe7c00c18247b55b5813e02f81de6527cf2c56da948d0cb87d872484f9e5ce33e4a19316c44281afd71ee3b38341bfb7522f

test:
  secret_key_base: 463d76b50acbd78888f8b65e29bef9ae0ca7730d458e50d576fe8a31e8174a54b45c69f15c5b809142fbc0f5607e1214bebcf2b92a7b83c10cd99926ec091419

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
